webapp/backend_rails/config/routes.rb
Rails.application.routes.draw do
  get 'api/login'
  get 'api/logout'
  get 'api/mood'

  resources :moods

end

webapp/backend_rails/app/models/mood.rb
class Mood < ActiveRecord::Base
  validates :level, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2}

  def as_json(options)
    data = { level: self.level, created_at: self.created_at.iso8601 }
    data[:comment] = self.comment if self.comment.present?
    data
  end
end

webapp/backend_rails/app/controllers/api_controller.rb
class ApiController < ApplicationController
  def login
  end

  def logout
  end

  def mood
    mood_sum = Mood.all.map {|m| m.level}.inject(:+)
    average = mood_sum.to_f / Mood.count

    respond_to do |format|
      format.json { render json: {average_mood: average} }
    end
  end
end

webapp/backend_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webapp/backend_rails/app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to moods_path, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:level, :comment)
    end
end

webapp/backend_rails/app/helpers/api_helper.rb
module ApiHelper
end

webapp/backend_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/backend_rails/app/helpers/moods_helper.rb
module MoodsHelper
end

webapp/backend_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackendRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

webapp/backend_rails/app/views/moods/_form.html.haml
= form_for @mood do |f|
  - if @mood.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mood.errors.count, "error")} prohibited this mood from being saved:"
      %ul
        - @mood.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :comment
    = f.text_field :comment
  .actions
    = f.submit 'Save'

webapp/backend_rails/app/views/moods/edit.html.haml
%h1 Editing mood

= render 'form'

= link_to 'Show', @mood
\|
= link_to 'Back', moods_path

webapp/backend_rails/app/views/moods/index.html.haml
%h1 Listing moods

%table
  %thead
    %tr
      %th Level
      %th Comment
      %th
      %th
      %th

  %tbody
    - @moods.each do |mood|
      %tr
        %td= mood.level
        %td= mood.comment
        %td= link_to 'Show', mood
        %td= link_to 'Edit', edit_mood_path(mood)
        %td= link_to 'Destroy', mood, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Mood', new_mood_path

webapp/backend_rails/app/views/moods/new.html.haml
%h1 New mood

= render 'form'

= link_to 'Back', moods_path

webapp/backend_rails/app/views/moods/show.html.haml
%p#notice= notice

%p
  %b Level:
  = @mood.level
%p
  %b Comment:
  = @mood.comment

= link_to 'Edit', edit_mood_path(@mood)
\|
= link_to 'Back', moods_path